name = "CleanUpPullRequestPreviews"
uuid = "06c59129-2005-40e8-8e6e-18d91e04568a"
authors = ["Brown Center for Biomedical Informatics"]
version = "0.1.0-DEV"

[deps]
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
GitHub = "5.1.6"
HTTP = "0.8.16"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
