name = "CleanUpPullRequestPreviews"
uuid = "06c59129-2005-40e8-8e6e-18d91e04568a"
authors = ["Brown Center for Biomedical Informatics"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
